name = "bilibili-comments"
main = "src/worker.ts"
# 必须使用较新的日期来开启 Node.js 兼容性
compatibility_date = "2025-12-19" 

# 开启 2025 年标准的 Node.js 兼容层
compatibility_flags = [ "nodejs_compat" ]

# 需要配置的 Secrets (使用 wrangler secret put MONGO_URI)
# MONGO_URI: MongoDB 连接字符串